version: "3.8"
services:
  wds-www:
    image: "ghassanaldarwish/wds-www"
    restart: unless-stopped
    networks:
      - app-workspace-network
      - frontend
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wds-www.rule=Host(`webdrei.com`)"
      - "traefik.http.routers.wds-www.entrypoints=websecure"
      - "traefik.http.routers.wds-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wds-www.tls=true"
      # - traefik.http.routers.wds-www.tls.domains[0].main=webdrei.com
      # - traefik.http.routers.wds-www.tls.domains[0].sans=*.webdrei.com
      - "traefik.http.services.wds-www.loadbalancer.server.port=3000"
    env_file:
      - ../environment/wds-www/.env.local

networks:
  app-workspace-network:
    name: app-workspace-network

  frontend:
    name: frontend
